### ISSUE TITLE
elm-repl creates elm-stuff and elm-package.json in the current folder

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-repl#130]
This is unexpected and can lead to littering if the `elm-repl` is terminated forcefully. 

This also raises an issue if the user is in a folder where they don't have write permissions. 

Another problem created by this behavior is that if I try to run `elm-repl` in a folder that already has an `elm-package.json` the repl fails if the project was created for a previous version.  

I would have expected it to inform me that I'm currently in a project created for a different version but still run with the current core loaded. 

os: macOS Sierra 10.12.1 Beta
elm: 0.18-alpha

**Comment by evancz** [comment]
The point of the REPL is that you can explore your *project*. It's not just for playing around with expressions. That's why it is tied to an `elm-package.json`. If you just want to play around with the REPL, don't do it in an existing project.

I think it makes sense to refine this into a more specific recommendation.
