### ISSUE TITLE
[0.16] Cannot read property 'make' of undefined

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-repl#80]
Testing 0.16, I have some troubles running simple commands in the repl running on osX 10.11 El Capitan, after:
- installing 0.16
- removing ~/.elm
- created a fresh project

sources, package and artifacts are here: https://gist.github.com/Warry/c059d6fb522c837fb4b8

**Comment by evancz** [comment]
I have observed this as well now, the root cause appears to be [these lines](https://github.com/elm-lang/core/blob/master/src/Native/Runtime.js#L305-L309) because the definition of `Elm.Signal` is getting stripped out for some reason. If I use `elm-make` for a non-signal thing or `elm-repl` which is always non-signals, I see this error.

**Comment by evancz** [comment]
Okay, looks like the root was something else, but the fix is done now. I'm hoping to get a second alpha together that includes this fix soon.

**Comment by evancz** [comment]
Thanks for trying out the alpha and reporting this!

**Comment by proehlen** [comment]
I'm just trying elm for the first time and this error is still happening in 0.16:
```
Peters-MacBook-Air:~ peter$ elm repl
---- elm repl 0.16.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1 + 1
TypeError: Cannot read property 'make' of undefined
```
